2025-04-17 02:57:44,901 - INFO - Loading Stanford Cars dataset...
2025-04-17 02:57:44,902 - INFO - Downloading Stanford Cars dataset from Kaggle...
2025-04-17 02:57:44,902 - ERROR - Error loading Stanford Cars dataset: Invalid model handle: jessicali9530/stanford-cars-dataset
2025-04-17 02:57:44,903 - ERROR - Failed to load dataset: Invalid model handle: jessicali9530/stanford-cars-dataset
Traceback (most recent call last):
  File "/home/lokmane-zed/project/DzVisionAi/back-end/src/ai/train_vehicle_model.py", line 467, in <module>
    main()
  File "/home/lokmane-zed/project/DzVisionAi/back-end/src/ai/train_vehicle_model.py", line 405, in main
    image_paths, color_labels, make_labels = load_stanford_cars_dataset()
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lokmane-zed/project/DzVisionAi/back-end/src/ai/train_vehicle_model.py", line 106, in load_stanford_cars_dataset
    kaggle_path = kagglehub.model_download("jessicali9530/stanford-cars-dataset")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lokmane-zed/anaconda3/lib/python3.12/site-packages/kagglehub/models.py", line 33, in model_download
    h = parse_model_handle(handle)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lokmane-zed/anaconda3/lib/python3.12/site-packages/kagglehub/handle.py", line 195, in parse_model_handle
    raise ValueError(msg)
ValueError: Invalid model handle: jessicali9530/stanford-cars-dataset
